import { useEffect, useState } from 'react'
import { ArrowDown, ArrowUp, BookOpen, ClipboardPaste, Copy, GripVertical, Pencil, Plus, Save, Share2, Sparkles, Trash2, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import PageHeader from '../components/PageHeader'
import ExerciseAutocomplete from '../components/ExerciseAutocomplete'
import CustomExerciseForm from '../components/CustomExerciseForm'
import { db } from '../db/database'
import { importLiftyText, uid, workoutToLiftyText } from '../lib'
import type { BlockModel, ExerciseDefinition, IntervalMode, ReadyWorkoutModality, WorkoutBlock, WorkoutExercise, WorkoutTemplate } from '../types'

const now=()=>new Date().toISOString()
const labels:Record<BlockModel,string>={resistance:'Resistido',cardio:'Cardio',interval:'Intervalado'}
function exerciseFrom(e:ExerciseDefinition,model:BlockModel,order:number):WorkoutExercise{return{id:uid(),exerciseId:e.id!,exerciseName:e.name,kind:e.kind,order,sets:model==='resistance'?3:undefined,repsMin:model==='resistance'?10:undefined,repsMax:model==='resistance'?12:undefined,targetMinutes:model==='cardio'?20:undefined,targetDistanceKm:model==='cardio'&&e.kind==='cardio_distance'?5:undefined,workSeconds:model==='interval'?30:undefined,restSeconds:model==='interval'?15:undefined}}
function emptyBlock(order:number):WorkoutBlock{return{id:uid(),name:`Bloco ${order+1}`,model:'resistance',order,exercises:[]}}

export default function WorkoutsPage(){
 const nav=useNavigate();const[list,setList]=useState<WorkoutTemplate[]>([]);const[name,setName]=useState('');const[blocks,setBlocks]=useState<WorkoutBlock[]>([emptyBlock(0)]);const[editingId,setEditingId]=useState<number|null>(null);const[customBlock,setCustomBlock]=useState<string|null>(null);const[drag,setDrag]=useState<{block:number;exercise?:number}|null>(null);const[showEditor,setShowEditor]=useState(false);const[showTextImport,setShowTextImport]=useState(false);const[sharedText,setSharedText]=useState('')
 const load=async()=>setList((await db.workouts.toArray()).filter(w=>!w.archived).sort((a,b)=>a.name.localeCompare(b.name)));useEffect(()=>{void load()},[])
 const reset=()=>{setName('');setBlocks([emptyBlock(0)]);setEditingId(null);setCustomBlock(null)}
 const closeEditor=()=>{reset();setShowEditor(false)}
 const newWorkout=()=>{reset();setShowEditor(true);window.setTimeout(()=>document.getElementById('workout-editor')?.scrollIntoView({behavior:'smooth',block:'start'}),0)}
 const patchBlock=(id:string,patch:Partial<WorkoutBlock>)=>setBlocks(v=>v.map(b=>b.id===id?{...b,...patch}:b))
 const moveBlock=(i:number,d:number)=>setBlocks(v=>{const n=[...v];const j=i+d;if(j<0||j>=n.length)return v;[n[i],n[j]]=[n[j],n[i]];return n.map((b,k)=>({...b,order:k}))})
 const moveExercise=(bi:number,ei:number,d:number)=>setBlocks(v=>v.map((b,i)=>{if(i!==bi)return b;const xs=[...b.exercises],j=ei+d;if(j<0||j>=xs.length)return b;[xs[ei],xs[j]]=[xs[j],xs[ei]];return{...b,exercises:xs.map((x,k)=>({...x,order:k}))}}))
 const addExercise=(blockId:string,e:ExerciseDefinition)=>setBlocks(v=>v.map(b=>b.id===blockId?{...b,exercises:[...b.exercises,exerciseFrom(e,b.model,b.exercises.length)]}:b))
 const patchExercise=(blockId:string,id:string,patch:Partial<WorkoutExercise>)=>setBlocks(v=>v.map(b=>b.id===blockId?{...b,exercises:b.exercises.map(x=>x.id===id?{...x,...patch}:x)}:b))
 async function save(){if(!name.trim())return alert('Informe o nome do treino.');if(!blocks.length||blocks.some(b=>!b.exercises.length))return alert('Cada subbloco precisa ter ao menos um exercício.');const payload:WorkoutTemplate={name:name.trim(),formatVersion:4,blocks:blocks.map((b,i)=>({...b,order:i,exercises:b.exercises.map((x,j)=>({...x,order:j,restSeconds:b.model==='interval'&&j===b.exercises.length-1?0:x.restSeconds}))})),archived:false,createdAt:now(),updatedAt:now()};if(editingId){const old=await db.workouts.get(editingId);await db.workouts.put({...payload,id:editingId,createdAt:old?.createdAt||payload.createdAt})}else await db.workouts.add(payload);reset();setShowEditor(false);await load()}
 async function duplicate(w:WorkoutTemplate){const x=structuredClone(w);delete x.id;x.name+=` - cópia`;x.createdAt=now();x.updatedAt=x.createdAt;x.blocks=x.blocks.map((b,i)=>({...b,id:uid(),order:i,exercises:b.exercises.map((e,j)=>({...e,id:uid(),order:j}))}));await db.workouts.add(x);await load()}
 async function saveReady(w:WorkoutTemplate){const duration=Number(prompt('Duração: 30, 45 ou 60 minutos','45'));if(![30,45,60].includes(duration))return;const modality=(prompt('Modalidade: resistance, functional, cross_training, hiit ou hybrid','hybrid')||'hybrid') as ReadyWorkoutModality;if(!['resistance','functional','cross_training','hiit','hybrid'].includes(modality))return alert('Modalidade inválida.');const copy=structuredClone(w);delete copy.id;await db.readyWorkouts.add({name:w.name,modality,durationMinutes:duration as 30|45|60,source:'personal',workoutTemplate:copy,createdAt:now(),updatedAt:now()});alert('Salvo em Treinos Prontos pessoais.')}
 async function copyText(text:string){try{await navigator.clipboard.writeText(text);return true}catch{const a=document.createElement('textarea');a.value=text;a.style.position='fixed';a.style.opacity='0';document.body.appendChild(a);a.select();const ok=document.execCommand('copy');a.remove();return ok}}
 async function shareWorkout(w:WorkoutTemplate){const text=workoutToLiftyText(w);if(navigator.share){try{await navigator.share({title:`Treino LIFTY - ${w.name}`,text});return}catch(err){if(err instanceof DOMException&&err.name==='AbortError')return}}const ok=await copyText(text);alert(ok?'Treino copiado. Agora é só colar e enviar para outra pessoa.':'Não foi possível copiar o treino automaticamente.')}
 async function importText(){if(!sharedText.trim())return alert('Cole o texto do treino LIFTY.');try{const ids=await importLiftyText(sharedText);setSharedText('');setShowTextImport(false);await load();alert(`${ids.length} treino(s) importado(s) com sucesso.`)}catch(err){alert(err instanceof Error?err.message:'Texto de treino inválido ou incompatível.')}}
 return <div className="page"><PageHeader title="Meus Treinos" subtitle="Crie, organize e gerencie seus treinos"/><div className="feature-grid workout-main-actions"><button className="card feature-button" onClick={newWorkout}><Plus/><div><strong>Novo treino</strong><small>Crie um treino híbrido</small></div></button><button className="card feature-button" onClick={()=>nav('/treinos/ia-import')}><Sparkles/><div><strong>IA Treino Import</strong><small>Crie com IA e importe para o LIFTY</small></div></button><button className="card feature-button" onClick={()=>nav('/treinos/prontos')}><BookOpen/><div><strong>Treinos Prontos</strong><small>Biblioteca separada de modelos</small></div></button></div>
 <div className="conventional-import"><button className="secondary compact-import" onClick={()=>setShowTextImport(v=>!v)}><ClipboardPaste size={17}/>Importar treino por texto</button></div>{showTextImport&&<section className="card text-import-card"><div className="section-title-row"><div><h2>Importar treino</h2><small>Cole abaixo um texto no formato LIFTY recebido de outra pessoa ou gerado por IA.</small></div><button className="icon-btn" onClick={()=>setShowTextImport(false)}><X size={18}/></button></div><textarea rows={12} value={sharedText} onChange={e=>setSharedText(e.target.value)} placeholder="=== LIFTY WORKOUT === ..."/><button className="primary full" onClick={()=>void importText()}><ClipboardPaste size={18}/>Importar treino</button></section>}
 {showEditor&&<section id="workout-editor" className="card workout-editor"><div className="section-title-row"><h2>{editingId?'Editar treino':'Novo treino'}</h2><button className="icon-btn" onClick={closeEditor}><X size={18}/></button></div><label>Nome do treino<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Treino completo A"/></label>
 <div className="stack">{blocks.map((b,bi)=><article className="subblock" key={b.id} draggable onDragStart={()=>setDrag({block:bi})} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(drag && drag.exercise===undefined && drag.block!==bi){const n=[...blocks],item=n.splice(drag.block,1)[0];n.splice(bi,0,item);setBlocks(n.map((x,i)=>({...x,order:i})));setDrag(null)}}}><div className="subblock-head"><GripVertical/><strong>Subbloco {bi+1}</strong><div className="actions"><button className="icon-btn" onClick={()=>moveBlock(bi,-1)}><ArrowUp size={16}/></button><button className="icon-btn" onClick={()=>moveBlock(bi,1)}><ArrowDown size={16}/></button><button className="icon-btn danger" disabled={blocks.length===1} onClick={()=>setBlocks(v=>v.filter(x=>x.id!==b.id).map((x,i)=>({...x,order:i})))}><Trash2 size={16}/></button></div></div><div className="field-grid two"><label>Nome do subbloco<input value={b.name} onChange={e=>patchBlock(b.id,{name:e.target.value})}/></label><label>Modelo do bloco<select value={b.model} onChange={e=>{const model=e.target.value as BlockModel;patchBlock(b.id,{model,intervalMode:model==='interval'?'custom':undefined,rounds:model==='interval'?3:undefined,roundRestSeconds:model==='interval'?60:undefined,countdownSeconds:model==='interval'?3:undefined,exercises:b.exercises.map((x,i)=>({...x,...exerciseFrom({id:x.exerciseId,name:x.exerciseName,kind:x.kind,system:true},model,i),id:x.id,exerciseId:x.exerciseId,exerciseName:x.exerciseName,kind:x.kind}))})}}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div>
 {b.model==='interval'&&<div className="field-grid three"><label>Modelo intervalado<select value={b.intervalMode||'custom'} onChange={e=>patchBlock(b.id,{intervalMode:e.target.value as IntervalMode})}><option value="tabata">Tabata</option><option value="emom">EMOM</option><option value="amrap">AMRAP</option><option value="custom">Personalizado</option></select></label><label>Ciclos/rodadas<input type="number" min="1" value={b.rounds||1} onChange={e=>patchBlock(b.id,{rounds:+e.target.value})}/></label><label>Descanso entre ciclos (s)<input type="number" min="0" value={b.roundRestSeconds||0} onChange={e=>patchBlock(b.id,{roundRestSeconds:+e.target.value})}/></label>{(b.intervalMode==='amrap'||b.intervalMode==='emom')&&<label>Duração total (min)<input type="number" min="1" value={b.totalMinutes||''} onChange={e=>patchBlock(b.id,{totalMinutes:+e.target.value})}/></label>}</div>}
 <ExerciseAutocomplete onSelect={e=>addExercise(b.id,e)}/><button className="secondary full" onClick={()=>setCustomBlock(customBlock===b.id?null:b.id)}><Plus size={16}/>Cadastrar exercício</button>{customBlock===b.id&&<CustomExerciseForm onCreated={e=>{addExercise(b.id,e);setCustomBlock(null)}}/>}
 <div className="exercise-list">{b.exercises.map((x,ei)=><div className="exercise-config" key={x.id} draggable onDragStart={e=>{e.stopPropagation();setDrag({block:bi,exercise:ei})}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.stopPropagation();if(drag && drag.exercise!==undefined && drag.block===bi && drag.exercise!==ei){const xs=[...b.exercises],item=xs.splice(drag.exercise,1)[0];xs.splice(ei,0,item);patchBlock(b.id,{exercises:xs.map((z,i)=>({...z,order:i}))});setDrag(null)}}}><div className="exercise-head"><div><GripVertical size={16}/><strong>{ei+1}. {x.exerciseName}</strong></div><div className="actions"><button className="icon-btn" onClick={()=>moveExercise(bi,ei,-1)}><ArrowUp size={15}/></button><button className="icon-btn" onClick={()=>moveExercise(bi,ei,1)}><ArrowDown size={15}/></button><button className="icon-btn danger" onClick={()=>patchBlock(b.id,{exercises:b.exercises.filter(y=>y.id!==x.id).map((y,i)=>({...y,order:i}))})}><Trash2 size={16}/></button></div></div>
 {b.model==='resistance'&&<div className="field-grid three"><label>Séries<input type="number" min="1" value={x.sets||''} onChange={e=>patchExercise(b.id,x.id,{sets:+e.target.value})}/></label><label>Rep. mín.<input type="number" value={x.repsMin||''} onChange={e=>patchExercise(b.id,x.id,{repsMin:+e.target.value})}/></label><label>Rep. máx.<input type="number" value={x.repsMax||''} onChange={e=>patchExercise(b.id,x.id,{repsMax:+e.target.value})}/></label></div>}
 {b.model==='cardio'&&<div className="field-grid two"><label>Tempo (min)<input type="number" value={x.targetMinutes||''} onChange={e=>patchExercise(b.id,x.id,{targetMinutes:+e.target.value})}/></label><label>Distância (km)<input type="number" step="0.1" value={x.targetDistanceKm||''} onChange={e=>patchExercise(b.id,x.id,{targetDistanceKm:+e.target.value})}/></label></div>}
 {b.model==='interval'&&<div className="field-grid three"><label>Trabalho (s)<input type="number" min="1" value={x.workSeconds||''} onChange={e=>patchExercise(b.id,x.id,{workSeconds:+e.target.value})}/></label><label>Descanso (s)<input type="number" min="0" disabled={ei===b.exercises.length-1} value={ei===b.exercises.length-1?0:(x.restSeconds||0)} onChange={e=>patchExercise(b.id,x.id,{restSeconds:+e.target.value})}/></label><label>Repetições alvo<input type="number" min="0" value={x.targetReps||''} onChange={e=>patchExercise(b.id,x.id,{targetReps:+e.target.value})}/></label></div>}</div>)}</div></article>)}</div>
 <button className="secondary full" onClick={()=>setBlocks(v=>[...v,emptyBlock(v.length)])}><Plus size={17}/>Adicionar subbloco</button><button className="primary full" onClick={save}><Save size={18}/>{editingId?'Salvar alterações':'Criar treino'}</button></section>}
 <section className="stack"><h2>Seus treinos</h2>{list.map(w=><article className="card compact" key={w.id}><div className="section-title-row"><div><h3>{w.name}</h3><small>{w.blocks.length} subbloco(s) • {w.blocks.reduce((a,b)=>a+b.exercises.length,0)} exercícios</small></div><div className="actions"><button className="icon-btn" onClick={()=>{setEditingId(w.id!);setName(w.name);setBlocks(structuredClone(w.blocks));setShowEditor(true);window.setTimeout(()=>document.getElementById('workout-editor')?.scrollIntoView({behavior:'smooth',block:'start'}),0)}}><Pencil size={17}/></button><button className="icon-btn" onClick={()=>duplicate(w)}><Copy size={17}/></button><button className="icon-btn" title="Compartilhar treino" onClick={()=>void shareWorkout(w)}><Share2 size={17}/></button><button className="icon-btn" onClick={()=>saveReady(w)}><BookOpen size={17}/></button><button className="icon-btn danger" onClick={async()=>{if(confirm(`Excluir “${w.name}”? O histórico será preservado.`)){await db.workouts.delete(w.id!);await load()}}}><Trash2 size={17}/></button></div></div><div className="chip-row">{w.blocks.map(b=><span className="chip" key={b.id}>{b.name} • {labels[b.model]}</span>)}</div></article>)}</section></div>
}
